name: mma

channels:
  - conda-forge

dependencies:
  - python=3.8
  - auto-sklearn
  - pip
  - dask
  - h2o
  - pip:
    - ploomber
    - pandas
    - scikit-learn
    # if using S3...
    # - boto3
    # if using Google Cloud Storage...
    # - google-cloud-storage
#blosc
#cloudpickle
#dask
#distributed
#lz4
#msgpack
#numpy
#pandas
#python
#toolz