meta:
#    import_tasks_from: features.yaml

    # Extract upstream dependencies from source code. If False, tasks
    # must declare dependencies using the "upstream" key
    extract_upstream: False

    # Extract product from source code. If False, tasks must have a "product" key
    extract_product: False

executor: serial

tasks:
    - source: tasks/preprocess.py
      name: preprocess
      upstream: null
      product:
         nb: reports/preprocess.ipynb
         data: products/data/preprocessed.csv

    - source: tasks/exploratory.py
      name: exploratory
      upstream: [preprocess]
      product:
        nb: reports/exploratory.ipynb
        data: products/data/exploratory.csv