meta:
#    import_tasks_from: features.yaml

    # Extract upstream dependencies from source code. If False, tasks
    # must declare dependencies using the "upstream" key
    extract_upstream: False

    # Extract product from source code. If False, tasks must have a "product" key
    extract_product: False

executor: serial

tasks:
    - source: func.util.data_transform
      name: data-transform
      upstream: null
      product: products/data/data.csv
      params:
        file_path: '{{root}}/{{DATA_FILEPATH}}'

    - source: scripts/features.py
      name: features
      upstream: [data-transform]
      product:
        data: products/data/features.csv
        nb: products/reports/features.ipynb
      params:
        features: '{{features_odds}}'
        target: '{{TARGET}}'

    - source: scripts/nested_cv.py
      name: nested-cv
      upstream: [ features ]
      product:
        nb: products/reports/nested_cv.ipynb
        model: products/models/nested_cv.pt
      params:
        target: '{{TARGET}}'
        odds_cols: '{{ODDS_COLS}}'
        random_seed: '{{RANDOM_SEED}}'
        test_ratio: 0.2
        inner_splits: 2
        outer_splits: 5
